### ISSUE TITLE
Allow alternate apiserver port

### ISSUE THREAD

**Issue by thefinn93** [poseidon/terraform-render-bootkube#42]
I would like to use port 443 for ingress to the containers, but `terraform-render-bootkube` has the apiserver port set to 443 with no option to change it. Is this something that you would be interested in adding? I'm not opposed to doing it myself and making a PR, but I would like feedback about if this is a reasonable idea first.

**Comment by dghubble** [comment]
Ingress controllers are run on workers, like other workloads. https://typhoon.psdn.io/addons/ingress/

In the future there may be a coordinated shift in Typhoon to use 6443 for the apiserver on all platforms ( a convention more distros are going with). It needs to be coordinated because firewalls and load balancers must align and any physical load balancers must actually be changed. Appropriate migration docs will be provided at that time.

**Comment by dghubble** [comment]
rel: #17

**Comment by thefinn93** [comment]
Ah, sorry i didn't see #17, I guess that settles that. Thanks
