### ISSUE TITLE
Separate internal and external apiserver_port 

### ISSUE THREAD

**Issue by rporres** [poseidon/terraform-render-bootkube#72]
`apiserver_port` variable is used to define internal port where api server listens and the external port that all controllers and workers use reach the apiserver via kubeconfig. If there's a need for those ports to be different, e.g. there's a load balancer on top that uses a different port there's no way of doing this.

Change would be rather trivial to do and I'm totally happy to send a PR, but since `apiserver_port` is marked as _unofficial, temporary, may be removed without notice_ I'd preferred to create this issue first to know better which are the plans for that variable and if the change proposed makes sense.

**Comment by dghubble** [comment]
The aim is to move in the opposite direction - removing that variable, rather than supporting more.

Typhoon v1.10.5 switched `kube-apiserver` (along with load balancers, firewall rules, and security groups) from using 443 to 6443 across bare-metal, AWS, and DigitalOcean. The `terraform-render-bootkube` module only has an "unofficial, temporary, may be removed without notice" `apiserver_port` variable since Google Cloud TCP proxies still whitelist only certain ports (and don't include the Kubernetes default 6443). Otherwise, you shouldn't have trouble using 6443 now.

Once there is a solution on Google Cloud, the `terraform-render-bootkube` `apiserver_port` will be dropped. Typhoon clusters will all use 6443. `kube-apiserver` manifests can drop privileges that were only for low port binding. There's no intention of supporting a configuration option here.

Also, this move wasn't taken lightly or just to cause trouble. It helped enable the load balancer consolidations in v1.10.5 that reduced costs of running clusters. Alignment with upstream and consistency across DO and bare-metal were nice-to-have's. 

* https://github.com/poseidon/typhoon/pull/248
* https://github.com/poseidon/terraform-render-bootkube/pull/67
* https://github.com/poseidon/typhoon/pull/271

**Comment by rporres** [comment]
Thanks for your detailed answer!

> The aim is to move in the opposite direction - removing that variable, rather than supporting more.

I was suspecting something like that seeing the comment in the file :)

Let me explain our use case and why we need a way to specify that the LB port needs to be different than the api process port

We're deploying kubernetes in baremetal, using a provider that does not have an offer of load balancers. In order to have apiserver HA our best and safest option is to use a combination of HAProxy (with the apiservers as backends) and keepalived (to have a floating ipaddress) that is working very well. HAProxy and apiservers run in the same servers (as it doesn't make sense to deploy HAproxy in different servers), hence we need to be able to specify different ports (we don't need them to be privileged, just to be different)

`apiserver_port` is used for two different things: specify where the api servers listens and build the `server` url. I'm totally fine with api server listening in a well-known port, just as long as I can somehow specify the port to connect to the API servers LB. Or it could be other way around.

There's no official solution for API servers HA when going baremetal (last time I checked it recommended setting up an external LB). In order to use a round-robin DNS address (which would fit the schema of having just one port) I would need something to update the DNS register when one of the servers is down which is something that it is also not trivial to set. My experience with that kind of set-ups is with Consul, which is definitely overdoing things for our case :)

**Comment by rporres** [comment]
Have you had the chance to look into this, @dghubble ?

**Comment by dghubble** [comment]
Yes I've thought about it.

The module's `k8s_domain_name` handles the typical bare-metal multi-master use cases - where a DNS record should resolve to the master node(s). Everyone's bare-metal setup is different, so that interface covers both the simplistic round-robin DNS (poor man's "load balancer") or any external load balancer (hardware or software) that can point to the apiserver backends.

I get that you're running HA proxy directly on the master nodes, so there is effectively contention for the load balancer and apiserver (balanced application) for the same port 6443. You could experiment with this using the Typhoon module as usual, running `terraform apply`, and then before powering on instances, modify the two generated kubeconfig files in `assets_dir/cluster_name/auth/` to change 6443 to the external port you have HAproxy listening on. Then, all kubelet's and users will reach the apiserver through your HAproxy. This is more of a workaround than proper support - if you re-run `terraform apply` later, it will change the ports in those two generated files back to 6443.

If that suits your needs, you should probably just create a fork with those two tweaks to the generated kubeconfigs. I'm not wanting to mainline this as a feature, I don't have a great way to support it.

Before you go do that, why are you running HAproxy on the master nodes to begin with? Is there not a shared set of separate HAproxy nodes providing load balancing service for a variety of components (e.g. presumably Kubernetes isn't the first user) on that site? Or its for cost saving? I don't use HAproxy personally (so maybe I'm missing something).

**Comment by rporres** [comment]
Apologies for the late answer, I was on vacations and made the conscious decision to leave laptop at home :)

> If that suits your needs, you should probably just create a fork with those two tweaks to the generated kubeconfigs. I'm not wanting to mainline this as a feature, I don't have a great way to support it.

Fair enough. My current approach is to use and maintain a fork where you can set the internal and external api port. Default value is of course 6443, just to make things work as mainline if nothing is specified. I prefer doing that than touching files once they've been generated, that's just asking for trouble

> Before you go do that, why are you running HAproxy on the master nodes to begin with? Is there not a shared set of separate HAproxy nodes providing load balancing service for a variety of components (e.g. presumably Kubernetes isn't the first user) on that site? Or its for cost saving? I don't use HAproxy personally (so maybe I'm missing something).

I don't want to maintain three more servers just to run HAProxy as I don't have the need of it for anything else. It is an environment where we run everything on top of kubernetes, so balancing services are provided from it. HAProxy process is light enough to run in the same servers as we run k8s API.

**Comment by dghubble** [comment]
Its still my goal to eventually remove this port option (if Google Cloud TCP proxy balancers ever allow 6443). But for now, https://github.com/poseidon/terraform-render-bootkube/pull/141 may be to your liking or let you drop a patch for a while. Effectively standardizing on 6443 for the internal port, but leaving a way to have a differing external port.
